services:
  product-service:
    image: postgres:15
    container_name: product-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5420:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
  inventory-service:
    image: postgres:15
    container_name: inventory-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5419:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
  order-service:
    image: postgres:15
    container_name: order-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5418:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
  user-service:
    image: postgres:15
    container_name: user-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5417:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
  payment-service:
    image: postgres:15
    container_name: payment-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5416:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    ports:
      - "8181:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
volumes:
  product_data:
  inventory_data:
  order_data:
  user_data:
  payment_data:
