spring:
  main:
    allow-circular-references: true
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5417/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
api.prefix: /api/v1
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
management:
  tracing:
    sampling:
      probability: 1.0